spin_manifest_version = 2

[application]
name = "alberguecarrascalejo"
version = "0.1.0"
authors = ["Guillermo Lam <guillermo@alberguedelcarrascalejo.com>"]

[variables]
auth0_domain = { required = true }
auth0_client_id = { required = true }
auth0_client_secret = { required = true }
booking_api_url = { default = "http://localhost:3001" }
reviews_api_url = { default = "http://localhost:3002" }

[[trigger.http]]
route = "/login"
component = "gateway"

[[trigger.http]]
route = "/callback"
component = "gateway"

[[trigger.http]]
route = "/logout"
component = "gateway"

[[trigger.http]]
route = "/booking/..."
component = "gateway"

[[trigger.http]]
route = "/reviews/..."
component = "gateway"

[[trigger.http]]
route = "/health"
component = "gateway"

[[trigger.http]]
route = "/..."
component = "frontend"

[component.gateway]
source = "target/wasm32-wasi/release/gateway.wasm"
[component.gateway.build]
command = "cargo build --target wasm32-wasi --release"
allowed_outbound_hosts = [ "https://{{ auth0_domain }}", "{{ booking_api_url }}", "{{ reviews_api_url }}" ]
[component.gateway.variables]
auth0_domain = "{{ auth0_domain }}"
auth0_client_id = "{{ auth0_client_id }}"
auth0_client_secret = "{{ auth0_client_secret }}"
booking_api_url = "{{ booking_api_url }}"
reviews_api_url = "{{ reviews_api_url }}"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:5bf5abc1f6b93f4e5b6e4b6b7b9e3e1d6b5b2b2b8a8a8a8a8a8a8a8a8a8a8a8a" }
files = [ { source = "frontend/dist", destination = "/" } ]