spin_manifest_version = 2

[application]
name = "albergue-app"
version = "0.1.0"
authors = ["Guillermo Lam <guillermo@alberguedelcarrascalejo.com>"]

[[trigger.http]]
route = "/api/..."
component = "gateway"

[[component]]
id = "gateway"
source = "gateway/spin_component.js"
[component.build]
command = "npm run build:gateway"