[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Spin SDK for WASM gateway
spin-sdk = "2.1"
wit-bindgen = "0.25"

# HTTP handling
http = "1.1"
url = "2.5"

# JSON and serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# JWT authentication
jsonwebtoken = "9.3"

# Async runtime
tokio = { version = "1.37", features = ["macros", "rt"] }
futures = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
log = "0.4"

[dependencies.shared]
path = "../services/shared"

[[bin]]
name = "gateway"
path = "src/main.rs"