[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30.0"
http = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

[package.metadata.component]
package = "component:gateway"

[package.metadata.component.dependencies]