spin_manifest_version = "1"

[application]
name = "basic-gateway"
version = "0.1.0"

[[component]]
id = "reviews"
source = "component.wasm"
[component.trigger]
route = "/api/reviews/..."

[[component]]
id = "health"
source = "component.wasm"
[component.trigger]
route = "/api/health"