spin_manifest_version = "1"

[application]
name = "albergue-gateway"
version = "0.1.0"
authors = ["Albergue Del Carrascalejo"]

[[component]]
id = "gateway-bff"
source = "bff/target/wasm32-wasi/release/gateway_bff.wasm"
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "bff"