spin_manifest_version = "2"

[application]
name = "gateway"
version = "0.1.0"

[variables]
auth0_domain = { required = true }
auth0_client_id = { required = true }
auth0_client_secret = { required = true }

[[trigger.http]]
route = "/api/..."
component = "gateway-bff"

[[trigger.http]]
route = "/api/reviews/..."
component = "reviews-service"

[[trigger.http]]
route = "/..."
component = "static-files"

[component.gateway-bff]
source = "bff/target/wasm32-wasi/release/gateway_bff.wasm"
[component.gateway-bff.build]
workdir = "bff"
command = "cargo build --release --target wasm32-wasi"
[component.gateway-bff.variables]
auth0_domain = "{{ auth0_domain }}"
auth0_client_id = "{{ auth0_client_id }}"
auth0_client_secret = "{{ auth0_client_secret }}"

[component.reviews-service]
source = "../services/reviews-service/target/wasm32-wasi/release/reviews_service.wasm"
[component.reviews-service.build]
workdir = "../services/reviews-service"
command = "cargo build --release --target wasm32-wasi"

[component.static-files]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:5bf5abc1f6b93f4e5b6e4b6b7b9e3e1d6b5b2b2b8a8a8a8a8a8a8a8a8a8a8a8a" }
files = [ { source = "../frontend/dist", destination = "/" } ]