spin_manifest_version = "2"

[application]
name = "gateway"
version = "0.1.0"

[variables]
auth0_domain = { required = true }
auth0_client_id = { required = true }
auth0_client_secret = { required = true }

[[trigger.http]]
route = "/api/security/..."
component = "security-service"

[[trigger.http]]
route = "/api/rate-limit/..."
component = "rate-limiter-service"

[[trigger.http]]
route = "/api/auth/..."
component = "auth-verify"

[[trigger.http]]
route = "/api/booking/..."
component = "booking-service"

[[trigger.http]]
route = "/api/reviews/..."
component = "reviews-service"

[[trigger.http]]
route = "/..."
component = "static-files"

[component.security-service]
source = "bff/security_service/target/wasm32-wasi/release/security_service.wasm"
[component.security-service.build]
workdir = "bff/security_service"
command = "cargo build --release --target wasm32-wasi"
[component.security-service.variables]
auth0_domain = "{{ auth0_domain }}"
auth0_client_id = "{{ auth0_client_id }}"
auth0_client_secret = "{{ auth0_client_secret }}"

[component.rate-limiter-service]
source = "bff/rate_limiter_service/target/wasm32-wasi/release/rate_limiter_service.wasm"
[component.rate-limiter-service.build]
workdir = "bff/rate_limiter_service"
command = "cargo build --release --target wasm32-wasi"

[component.auth-verify]
source = "bff/auth_verify/target/wasm32-wasi/release/auth_verify.wasm"
[component.auth-verify.build]
workdir = "bff/auth_verify"
command = "cargo build --release --target wasm32-wasi"
[component.auth-verify.variables]
auth0_domain = "{{ auth0_domain }}"
auth0_client_id = "{{ auth0_client_id }}"
auth0_client_secret = "{{ auth0_client_secret }}"

[component.booking-service]
source = "bff/booking_service/target/wasm32-wasi/release/booking_service.wasm"
[component.booking-service.build]
workdir = "bff/booking_service"
command = "cargo build --release --target wasm32-wasi"

[component.reviews-service]
source = "../services/reviews-service/target/wasm32-wasi/release/reviews_service.wasm"
[component.reviews-service.build]
workdir = "../services/reviews-service"
command = "cargo build --release --target wasm32-wasi"

[component.static-files]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:5bf5abc1f6b93f4e5b6e4b6b7b9e3e1d6b5b2b2b8a8a8a8a8a8a8a8a8a8a8a8a" }
files = [ { source = "../frontend/dist", destination = "/" } ]