name = "albergue-backend"
main = "build/worker.js"
compatibility_date = "2023-05-18"

[env.production]
name = "albergue-backend-prod"

[env.staging]
name = "albergue-backend-staging"

[build]
command = "cargo build --release --target wasm32-unknown-unknown && wasm-bindgen --out-dir build --web target/wasm32-unknown-unknown/release/albergue_backend.wasm"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "rate-limits-kv"
preview_id = "rate-limits-kv-preview"

[vars]
ENVIRONMENT = "production"